---

- name: "deploying second screen node app"
  hosts: 'dev'
  become: yes
  become_method: sudo

  vars:
    app: "artofrawr_secondscreen"
    path: "/srv/artofrawr/secondscreen"
    repo: "https://github.com/artofrawr/demos.git"

  roles:
    - nodeapp